sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t faizulhai24/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true faizulhai24/docker-react npm run test